# Secrets para o Streamlit
# Este arquivo contém as chaves de API necessárias

[custom]
google_api_key = "AIzaSyAVwh4gsg8NBBtb5E6VIwJzr6zuzJkIEh4"
supabase_url = "https://fqrercjjyqdsigcjbmgi.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcmVyY2pqeXFkc2lnY2pibWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjgyNzYsImV4cCI6MjA3NTUwNDI3Nn0.TUzeich5dp7LiUvm924tvEayZald8XXku4-3ldQw1gY"
